### ISSUE TITLE
UI labels doesn't display

### ISSUE THREAD

**Issue by bird0912** [greatest-ape/OctaSine#10] opened 2021-06-17 13:05 UTC
In OctaSine 0.5.1 the labels of the user interface doesn't appear. The other elements are fine, it's just the texts that are missing.
Windows 10 inside Reaper 6 DAW. The problem is immediate from the loading of the VST.
[OctaSine.log](https://github.com/greatest-ape/OctaSine/files/6670376/OctaSine.log)

**Comment by greatest-ape** [comment] 2021-06-17 17:23
Thanks. That's very strange. Do parameter values appear? Could you please attach a screenshot? Also, could you please try with version 0.5.0 and see if it works?

**Comment by bird0912** [comment] 2021-06-17 19:20
Of course! Yes, parameter values doesn't appear either:
![OctaSine UI Bug](https://user-images.githubusercontent.com/35444613/122459998-35774980-cf77-11eb-88ff-b315ce8574fe.png)

**Comment by bird0912** [comment] 2021-06-17 19:27
In version 0.5.0 the texts doesn't appear either. If any other help is needed I gladly will contribute :D

**Comment by greatest-ape** [comment] 2021-06-17 19:53
Thanks!

I found this iced issue which looks very similar: https://github.com/hecrj/iced/issues/537 . In your screenshot, I noticed that the modulation matrix doesn’t render properly. Canvas rendering issues seem to be present in the linked issue as well. Do you also happen to use an AMD integrated GPU?

**Comment by greatest-ape** [comment] 2021-06-17 20:45
One thing that you could do is to build and run https://github.com/hecrj/iced/tree/master/examples/bezier_tool and check if text is missing there too. Would you know how to do that?

**Comment by bird0912** [comment] 2021-06-17 21:54
Yes! I'm using an AMD integrated GPU. I will check if I can build the bezier tool :B

**Comment by greatest-ape** [comment] 2021-06-18 14:14
In that case, I think it’s reasonable to assume that the issue is the same, so you don’t really have to go through the trouble :-) 

I can try to build a copy of octasine without anti aliasing for you. It probably won’t look so great, but at least the text should be visible.

**Comment by bird0912** [comment] 2021-06-18 19:16
Oh wow, that's great news!!! Thank you very much :D

**Comment by greatest-ape** [comment] 2021-06-20 08:35
Please try this: [OctaSine-v0.5.1-Windows-No-Anti-Aliasing.zip](https://github.com/greatest-ape/OctaSine/files/6681941/OctaSine-v0.5.1-Windows-No-Anti-Aliasing.zip)

Also, I realized that it would actually make sense for you to try out the bezier tool, so I built it for you: [bezier_tool.zip](https://github.com/greatest-ape/OctaSine/files/6681940/bezier_tool.zip). If it doesn't look like the screen capture [here](https://github.com/hecrj/iced/tree/master/examples/bezier_tool), I would appreciate if you leave a comment with Windows version, name of your GPU and a screenshot [here](https://github.com/hecrj/iced/issues/537). It could help with eventually resolving the issue in OctaSine.

**Comment by bird0912** [comment] 2021-06-21 02:08
Excelent!!! I will give it a try :D

**Comment by greatest-ape** [comment] 2021-12-20 21:39
@bird0912 Could you please try with the latest release? https://github.com/greatest-ape/OctaSine/releases/tag/v0.5.4

**Comment by bird0912** [comment] 2021-12-21 12:05
Yes!!! Thanks in advance!

**Comment by bird0912** [comment] 2021-12-21 14:26
Excellent! I can see all the fonts! Thank you so much! Just one little
question, how can I resize the plugin? it's a bit small. Thank you again
for the great work :D

**Comment by greatest-ape** [comment] 2021-12-21 16:59
Great! And thanks for trying it out.

You can't resize it at the moment.. If I make the current size larger, it will be too large for laptop screens. I might add resizing, but it will probably be too difficult to make it work with how I construct the interface.

**Closed by greatest-ape** 2021-12-21 16:59 UTC
Labels: wgpu bug, windows
